### ISSUE TITLE
flashback

### ISSUE THREAD

**Issue by NingNingL** [dat-ng/ar-location-based-android#11]
The app can installed successfully. But when i open it , the app always flashback. The logcat is as below.

FATAL EXCEPTION: main
                                                   Process: ng.dat.ar, PID: 27374
                                                   java.lang.RuntimeException: setParameters failed
                                                       at android.hardware.Camera.native_setParameters(Native Method)
                                                       at android.hardware.Camera.setParameters(Camera.java:1953)
                                                       at ng.dat.ar.ARCamera.surfaceChanged(ARCamera.java:215)
                                                       at android.view.SurfaceView.updateWindow(SurfaceView.java:608)
                                                       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:179)
                                                       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5435)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by 19gauravk95** [comment]
What is the camera resolution you have set in the camera parameter?
And does your device support that camera resolution..!

Remember that not all devices support all resolution..so you will have to get the list of supported camera resolution and then set the resolution or any other parameters... accordingly.. otherwise usually app crashes...

There are multiple resources online to do so...

Hope it helps..

**Comment by candidobugarin** [comment]
Do you know where code is possible to set the camera resolution? Would it be the z_near and z_far parameters?

**Comment by 19gauravk95** [comment]
In the ARCamera.java Line 212. we have params.setPreviewSize(previewSize.width, previewSize.height);
Change the width and height to an appropriate one.
Try hardcoding it first like(choose one of the supported camera resolution by your device)
params.setPreviewSize(1280,720); //1280*720 resolution

Though getOptimalPreviewSize() in ARCamera line 167 is suppose to select an appropriated camera resolution of the device, it maybe not picking the right resolution in your case.
You can output the selected preview size and see if the selected resolution are the supported ones.

If this is also not helping, try checking for the other camera parameters like focus mode etc. See if making the orientation of the the activity to either landscape or portrait helps. Also check if camera permission is given.

Most of these think are already handled by the ARCamera.java but i guess there some issue in your case.

**Comment by brutallyminimal** [comment]
In ARCamera.java (Line 206) - replace your surfaceChanged() function with the following -

    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
        if(camera != null) {
            this.cameraWidth = width;
            this.cameraHeight = height;

            Camera.Size previewSize = supportedPreviewSizes.get(0);

            Camera.Parameters params = camera.getParameters();
            params.setPreviewSize(previewSize.width, previewSize.height);
            requestLayout();

            camera.setParameters(params);
            camera.startPreview();

            generateProjectionMatrix();
        }
    }

**Comment by anuloo** [comment]
is anyone manage to make it work in landscape at all?
changing camera size did not work for me.
Any example would appriciated
